[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "popcorn-scraper"
version = "1.0.0"
description = "Scraper générique de résultats pour Movie Keeper"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "curl_cffi>=0.7.0",
    "beautifulsoup4>=4.12.0",
]

[project.scripts]
# C'est l'équivalent du "bin" dans package.json
# Ça va créer une commande globale `popcorn-scrap` utilisable directement
popcorn-scrap = "popcorn_scraper.core:main"